### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Jiang-Mingfei** [wimh966/QDrop#17]
```
Traceback (most recent call last):
  File "../../../qdrop/solver/main_imagenet.py", line 124, in <module>
    main(args.config)
  File "../../../qdrop/solver/main_imagenet.py", line 112, in main
    recon_model(model, fp_model)
  File "../../../qdrop/solver/main_imagenet.py", line 110, in recon_model
    recon_model(child_module, getattr(fp_module, name))
  File "../../../qdrop/solver/main_imagenet.py", line 108, in recon_model
    reconstruction(model, fp_model, child_module, getattr(fp_module, name), cali_data, config.quant.recon)
  File "/code/QDrop-o/qdrop/solver/recon.py", line 121, in reconstruction
    fp_inp, fp_oup = save_inp_oup_data(fp_model, fp_module, cali_data, store_inp=True, store_oup=True, bs=config.batch_size, keep_gpu=config.keep_gpu)
  File "/code/QDrop-o/qdrop/solver/recon.py", line 36, in save_inp_oup_data
    cached[1] = torch.cat([x for x in cached[1]])
RuntimeError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 14.62 GiB total capacity; 9.48 GiB already allocated; 2.55 GiB free; 11.03 GiB reserved in total by PyTorch)

```
There is a problem of "out of memory", how much GPU memory does this code need? And how to train with multiple GPUs?

**Comment by wimh966** [comment]
Hello, may I kindly request what kind of model you are running? Inputs and outputs of blocks require large memory. By taking keep_gpu=False in the config file, they will be temporarily put on CPU to reduce the memory overhead. Then, devices such as 2080, 3090, V100, etc. will be available.

To train with multiple GPUs, you can refer to the branch "qdrop_coco" which runs object detection tasks with 8 GPUs.
