### ISSUE TITLE
Runtimerror in experiment on mmdetection

### ISSUE THREAD

**Issue by KenRamzes** [wimh966/QDrop#19]
Hi ! Thanks for your excellent work. When I try to reproduce the results based on mmdetection, there are some errors : RuntimeError: a leaf Variable that requires grad is being used in an in-place operation. Could you help me to solve those problems?
The detials are as follows:
Traceback (most recent call last):
  File "qdrop/solver/quant_coco.py", line 365, in <module>
Traceback (most recent call last):
  File "qdrop/solver/quant_coco.py", line 365, in <module>
    main()
  File "qdrop/solver/quant_coco.py", line 265, in main
    recon_model(model, fp_model, cali_data, q_config.recon)
      File "qdrop/solver/quant_coco.py", line 361, in recon_model
main()
  File "qdrop/solver/quant_coco.py", line 265, in main
    _recon_model(model, fp_model)
  File "qdrop/solver/quant_coco.py", line 359, in _recon_model
    recon_model(model, fp_model, cali_data, q_config.recon)
  File "qdrop/solver/quant_coco.py", line 361, in recon_model
    _recon_model(child_module, getattr(fp_module, name))
  File "qdrop/solver/quant_coco.py", line 359, in _recon_model
    _recon_model(model, fp_model)
  File "qdrop/solver/quant_coco.py", line 359, in _recon_model
    _recon_model(child_module, getattr(fp_module, name))
  File "qdrop/solver/quant_coco.py", line 357, in _recon_model
    _recon_model(child_module, getattr(fp_module, name))
  File "qdrop/solver/quant_coco.py", line 359, in _recon_model
    reconstruction(model, fp_model, child_module, getattr(fp_module, name), cali_data, recon_config)
  File "/QDrop-qdrop_coco/qdrop/solver/recon.py", line 148, in reconstruction
    _recon_model(child_module, getattr(fp_module, name))
  File "qdrop/solver/quant_coco.py", line 357, in _recon_model
    module_ddp = build_ddp(
  File "/QDrop-qdrop_coco/mmdet/utils/util_distribution.py", line 71, in build_ddp
    reconstruction(model, fp_model, child_module, getattr(fp_module, name), cali_data, recon_config)
  File "/QDrop-qdrop_coco/qdrop/solver/recon.py", line 148, in reconstruction
    return ddp_factory[device](model, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 580, in __init__
    module_ddp = build_ddp(
  File "/home/xiaojunrui/QDrop-qdrop_coco/mmdet/utils/util_distribution.py", line 71, in build_ddp
    return ddp_factory[device](model, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 580, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/home/xxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 597, in _sync_params_and_buffers
    self._sync_params_and_buffers(authoritative_rank=0)    
self._distributed_broadcast_coalesced(
  File "/home/xxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 597, in _sync_params_and_buffers
  File "/home/xxxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1334, in _distributed_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "/home/xxx/anaconda3/envs/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1334, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
    dist._broadcast_coalesced(
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2421226) of binary: /home/xxx/anaconda3/envs/bin/python

**Comment by wimh966** [comment]
Sorry for the late reply. May I kindly ask whether you have solved that? Otherwise, may I have your commands and other details?

**Comment by KenRamzes** [comment]
Thanks again for your work. This bug disappeared after changing mmcv version to 1.72

**Comment by wimh966** [comment]
Thanks for your reply. If you have any other questions, feel free to contact me.
